<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/12/28
 * Time: 16:47
 */

namespace app\controllers;


use yii\web\Controller;
use yii\web\Response;

class BaseController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::$app->getResponse()->on(Response::EVENT_BEFORE_SEND, [$this,'beforeSend']);
    }

    public function beforeSend($event)
    {
        $response = $event->sender;

        $isSuccessful = $response->isSuccessful;

        var_dump($response->statusCoce);die;
    }
}